project:
  type: website
  output-dir: docs
  preview: 
    port: 4040

website:
  title: "mve"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
  sidebar:
    contents: slides

format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true